spring:
  application:
    name: api-gateway
  profiles:
    active: "@profiles.active@"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Automatically create routes from service discovery
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/p/users/**

        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/api/p/movies/**, /api/p/shows/**, /api/p/seats/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**, /api/p/notifications/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**, /api/p/payments/**

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**, /api/p/bookings/**

        - id: booking-service-websocket
          uri: lb:ws://booking-service
          predicates:
            - Path=/api/p/ws
            - Header=Upgrade, websocket

  lifecycle:
    timeout-per-shutdown-phase: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

server:
  port: 8080
  shutdown: graceful

app:
  security:
    jwt:
      base64-secret-key: ZGN0LWJhc2Utc2VjcmV0LWtleS10b2tlbi12YWxpZGl0eS04NjQwMDAwMG1zLWZvci1yZW1lbWJlci1tZS04NjQwMDAwMG1z
      validity: 3600000 # 1 hour
      validity-for-remember: 604800000 # 7 days
