logging:
  level:
    root: info
    vn.ptit.moviebooking: info
    org.hibernate.sql: info
  charset:
    console: UTF-8
    file: UTF-8
  # Custom properties to define logs file paths according to different profiles
  file-path: /mnt/logs

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        show_sql: false
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    virtual-host: ${RABBIT_MQ_VIRTUAL_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
    exchange:
      direct: amq.direct
    producer:
      reply-timeout: 60000
    consumer:
      max-concurrent-consumer: 2
      concurrent-consumer: 2
      prefetch-count: 10
    queues:
      NOTIFICATION:
        name: queue.notifications
        routing-key: routingKey.notifications

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 5  # Heartbeat frequency
    lease-expiration-duration-in-seconds: 60  # Expiration time if no heartbeat received
    instanceId: ${spring.application.name}:${server.port}
