
spring:
  application:
    name: movie-service
  profiles:
    active: "@profiles.active@"

  jpa:
    open-in-view: false
    properties:
      hibernate:
        archive:
          autodetection: class
        show_sql: true
        format_sql: false
        jdbc:
          time_zone: UTC
          ddl-auto: update
        hibernate:
          # Hibernate only checks if the current schema matches the entity
          # If it does not match, the application will not start
          # Do not make any changes to the schema
          ddl-auto: update
  sql:
    init:
      mode: never

  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    virtual-host: ${RABBIT_MQ_VIRTUAL_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
    exchange:
      direct: amq.direct
    producer:
      reply-timeout: 60000
    consumer:
      max-concurrent-consumer: 2
      concurrent-consumer: 2
      prefetch-count: 10

axon:
  axonserver:
    servers: localhost:8124
    enabled: true
  eventhandling:
    processors:
      booking-saga:
        mode: subscribing
  amqp:
    exchange: amq.direct

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: db,ping
  health:
    db:
      enabled: true
